# cargo-features = ["trim-paths"]

[workspace]
members = ["zome"]
resolver = "2"

[workspace.dependencies]
hdi = "0.4.0-beta-dev"
hdk = "0.3.0-beta-dev"
holochain = "0.3.0-beta-dev"
serde = "1"

[profile.release]
opt-level = "z"
# trim-paths = true
codegen-units = 1
# remap-debuginfo = true
