[package]
name = "my_zome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]
name = "my_zome"

[dependencies]
hdk = "0.3.0-beta.dev"
serde = "1"
